spring.application.name: Yeodam

imp:
  store-key: imp65451236
  api-key: 1821116401505487
  secret-key: DH0KJWY8lzqX4lYLkHQUeelZ8OoxFZTLbfni89eKLmUjbYzv5m3AsMI6W71xa2CHNFcFUJ3U62LusAex

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/elice/project/yeodam
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  mvc:
    hiddenmethod:
      filter:
        enabled: true


  cloud:
    aws:
      credentials:
        accessKey: AKIAZQ3DR4M3OKBX277X
        secretKey: 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
      s3:
        bucket: kcabsohwsseug
      region:
        static: ap-northeast-2
      stack:
        auto: false
      cloudfront:
        domainName: djwm3h8i3zg0e.cloudfront.net

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace